const SET_IS_NO_CONNECTION_MODAL_OPEN = "SET_IS_NO_CONNECTION_MODAL_OPEN";
const SET_CONNECTION_FAILED_REQUESTS = "SET_CONNECTION_FAILED_REQUESTS";
const SET_IS_CONNECTION_MODAL_ALLOWED_TO_OPEN = "SET_IS_CONNECTION_MODAL_ALLOWED_TO_OPEN";

export { SET_IS_NO_CONNECTION_MODAL_OPEN, SET_CONNECTION_FAILED_REQUESTS, SET_IS_CONNECTION_MODAL_ALLOWED_TO_OPEN };
