const GET_VIDEO_PLAYER = "GET_VIDEO_PLAYER";
const GET_VIDEO_PLAYER_SUCCESS = "GET_VIDEO_PLAYER_SUCCESS";
const GET_VIDEO_PLAYER_FAIL = "GET_VIDEO_PLAYER_FAIL";
const CLEAR_VIDEO_PLAYER = "CLEAR_POLL_RESULT";

export { CLEAR_VIDEO_PLAYER, GET_VIDEO_PLAYER, GET_VIDEO_PLAYER_FAIL, GET_VIDEO_PLAYER_SUCCESS };
