const START_CONTINUE_WATCHING = "START_CONTINUE_WATCHING";
const UPDATE_CONTINUE_WATCHING = "UPDATE_CONTINUE_WATCHING";
const END_CONTINUE_WATCHING = "END_CONTINUE_WATCHING";

export { END_CONTINUE_WATCHING, START_CONTINUE_WATCHING, UPDATE_CONTINUE_WATCHING };
